### ISSUE TITLE
Crear boton para crear productos

### ISSUE THREAD

**Issue by Facundo-Rodriguezz** [Facundo-Rodriguezz/Full-Stack#5]

**Comment by Facundo-Rodriguezz** [comment]
tarea terminada

**Comment by Facundo-Rodriguezz** [comment]
configurar que aparezca el nombre de cada cosa que se agrega, sacar sku, y ver que "categorias" sea agregado tambien.

**Comment by nks21may** [comment]
Falta hacer commit backend.

**Comment by nks21may** [comment]
Cancelar limpia los campos.
Marcar en rojo el campo que falle o mostrar cartel de error o un Toastr

**Comment by Facundo-Rodriguezz** [comment]
tarea realizada
